"""Generates present-day (c. 1959) residents of the city, each grounded in
a specific piece of the generated history -- a place, its domain, its
founder, and a real recorded incident there -- rather than being generic
NPCs. The LLM is genuinely better at weaving specific facts into a natural
bio than a template is, so it's the primary path here (unlike the grammar-
first approach for the bulk of history generation); a plain fallback (its
sentence pools are the theme's `characters` section) still keeps this working with
Ollama offline. All of it -- prompts, templates, the present year -- comes
from the current theme (theme.py).

Each character also gets their own `history` -- a short chronological
list of `{year, gospel_text}` entries in the same shape as a Place's own
`history` (see entities.py), but spanning only *their* lifetime (birth to
c. 1959), generated by _generate_life_history() below. Deliberately
narrative-only: unlike events.py's engine, it never mutates place/figure
state, since a character can be generated well after the rest of the
history is already finalized.
"""

import random

import theme

from . import config
from . import entities
from . import llm
from . import names
from .eras import era_for_year


def _data() -> dict:
    # relationship_hints {"active", "gone"}, bio_templates, life_event_templates
    # {"early", "arrival", "recent"}, appearance_templates
    return theme.current()["characters"]


def _present_year() -> int:
    return theme.current().present_year


def _pick_grounding(places: list, figures: list, rng: random.Random, exclude: set,
                     force_place_id: str = None) -> dict:
    figures_by_id = {f.id: f for f in figures}
    if force_place_id:
        place = next((p for p in places if p.id == force_place_id), None)
        if place is None:
            raise ValueError(f"unknown place: {force_place_id!r}")
    else:
        candidates = [p for p in places if p.id not in exclude] or list(places)
        # Favor places with a richer recorded history -- more for a bio to draw on.
        weights = [len(p.history) + 1 for p in candidates]
        place = rng.choices(candidates, weights=weights, k=1)[0]
    founder = figures_by_id.get(place.founding_figure_id)
    anecdote = rng.choice(place.history) if place.history else None
    hints = _data()["relationship_hints"]["active"] if place.status == "active" else _data()["relationship_hints"]["gone"]
    return {
        "place": place, "founder": founder, "anecdote": anecdote,
        "relationship": rng.choice(hints),
    }


def _llm_character(grounding: dict, occupation: str = None, sex: str = None):
    place, founder, anecdote = grounding["place"], grounding["founder"], grounding["anecdote"]
    place_noun = entities.place_type_noun(place.place_type)
    t = theme.current()
    lines = [t.prompt("history.character_place", place=place.name, place_noun=place_noun,
                      founded=place.founded_year, domain=place.domain, status=place.status)]
    if founder:
        lines.append(t.prompt("history.character_founder", founder=founder.name, founder_role=founder.role.lower()))
    if anecdote:
        lines.append(t.prompt("history.character_anecdote", anecdote=anecdote["gospel_text"]))
    lines.append(t.prompt("history.character_relationship", relationship=grounding["relationship"]))
    if occupation:
        lines.append(t.prompt("history.character_occupation", occupation=occupation))
    if sex:
        lines.append(t.prompt("history.character_sex", sex=sex))

    constraint = ""
    if occupation:
        constraint += t.prompt("history.character_constraint_occupation", occupation=occupation)
    if sex:
        constraint += t.prompt("history.character_constraint_sex", sex=sex)

    prompt = t.prompt("history.character_dossier", history_lines="\n".join(lines), constraint=constraint)
    reply = llm.complete(prompt, temperature=0.95)

    fields = {}
    for line in reply.splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip().upper()
        if key in ("NAME", "AGE", "OCCUPATION", "QUIRK", "BIO"):
            fields[key] = value.strip()
    if not all(k in fields for k in ("NAME", "AGE", "OCCUPATION", "BIO")):
        return None

    digits = "".join(c for c in fields["AGE"] if c.isdigit())
    age = max(18, min(90, int(digits))) if digits else 40

    return {
        "id": entities.new_id("char_"),
        "name": fields["NAME"], "age": age,
        # A given occupation is used verbatim rather than trusting the
        # LLM's own OCCUPATION line -- it's a hard constraint, not a
        # suggestion, and the prompt already steered the bio to match it.
        "occupation": occupation or fields["OCCUPATION"],
        "quirk": fields.get("QUIRK", ""), "bio": fields["BIO"],
        "place_id": place.id, "place_name": place.name,
        "founder_id": founder.id if founder else None,
    }


def _fallback_character(grounding: dict, rng: random.Random,
                         occupation: str = None, sex: str = None) -> dict:
    place, founder = grounding["place"], grounding["founder"]
    t = theme.current()
    if not occupation:
        occupation = t.prompt("history.character_fallback_occupation_active" if place.status == "active"
                              else "history.character_fallback_occupation_gone", place=place.name)
    # `sex` isn't honored here -- the theme's name lists aren't split by
    # gender (a pre-existing limitation this grammar fallback shares with
    # historical-figure naming), so there's no signal to bias the name
    # pick on. Only the LLM path above can actually act on it.
    name = names.figure_name(era_for_year(_present_year()).id, occupation, rng)

    # Separate template pools per (still-standing vs. gone) x (has a known
    # founder to reference or not) -- each a complete, self-contained
    # sentence, so a "no blood relation" hint can never get a contradictory
    # "descended from" clause spliced into it, and {place} never dangles
    # awkwardly at a sentence's end.
    bio_templates = _data()["bio_templates"]
    if place.status == "active":
        pool = bio_templates["active_with_founder"] if founder else bio_templates["active_no_founder"]
    else:
        pool = bio_templates["gone_with_founder"] if founder else bio_templates["gone_no_founder"]
    relationship_sentence = rng.choice(pool).format(
        name=name, place=place.name, founder=founder.name if founder else "",
    )

    place_noun = entities.place_type_noun(place.place_type)
    appearance = rng.choice(_data()["appearance_templates"]).format(name=name)
    bio = t.prompt("history.character_fallback_bio", relationship_sentence=relationship_sentence, place=place.name,
                   place_noun=place_noun, domain=place.domain, first_name=name.split()[0], appearance=appearance)
    return {
        "id": entities.new_id("char_"),
        "name": name, "age": rng.randint(24, 72), "occupation": occupation,
        "quirk": t.prompt("history.character_fallback_quirk", domain=place.domain), "bio": bio,
        "place_id": place.id, "place_name": place.name,
        "founder_id": founder.id if founder else None,
    }


def _llm_life_history(character: dict, grounding: dict, rng: random.Random) -> list:
    """A short chronological personal timeline -- birth to now -- not the
    whole city's ~330-year history, just this one resident's own lifetime.
    Same LLM-first/grammar-fallback shape as the character dossier itself,
    and deliberately narrative-only: it never touches place/figure state
    (unlike the main event engine in events.py), since a character
    generated on demand, after the fact, shouldn't retroactively rewrite
    an already-finalized history other characters may already be grounded
    in."""
    place = grounding["place"]
    present = _present_year()
    birth_year = present - character["age"]
    count = rng.randint(4, 6)

    prompt = theme.current().prompt(
        "history.life_history", name=character["name"], age=character["age"], occupation=character["occupation"],
        present_year=present, birth_year=birth_year, bio=character["bio"], count=count,
        first_name=character["name"].split()[0], place=place.name)
    reply = llm.complete(prompt, temperature=0.9)

    events = []
    for line in reply.splitlines():
        if ":" not in line:
            continue
        year_part, _, text = line.partition(":")
        digits = "".join(c for c in year_part if c.isdigit())
        text = text.strip()
        if not digits or not text:
            continue
        year = max(birth_year, min(present, int(digits[:4])))
        events.append({"year": year, "gospel_text": text})
    events.sort(key=lambda e: e["year"])
    return events


def _fallback_life_history(character: dict, grounding: dict, rng: random.Random) -> list:
    place = grounding["place"]
    present = _present_year()
    birth_year = present - character["age"]
    span = max(present - birth_year, 1)

    # One event per life phase, in order, so even the offline fallback
    # reads as a real (if brief) arc rather than three unrelated facts.
    years = sorted([
        birth_year + rng.randint(0, max(span // 6, 1)),
        birth_year + span // 2 + rng.randint(-2, 2),
        present - rng.randint(0, max(span // 8, 1)),
    ])
    years = [max(birth_year, min(present, y)) for y in years]

    events = []
    for year, phase in zip(years, ("early", "arrival", "recent")):
        text = rng.choice(_data()["life_event_templates"][phase]).format(
            name=character["name"], place=place.name, domain=place.domain,
        )
        events.append({"year": year, "gospel_text": text})
    return events


def _generate_life_history(character: dict, grounding: dict, rng: random.Random) -> list:
    if config.LLM_FILL_NAMES and llm.available():
        try:
            events = _llm_life_history(character, grounding, rng)
            if events:
                return events
        except Exception:
            pass
    return _fallback_life_history(character, grounding, rng)


def generate_characters(places: list, figures: list, count: int = 10, seed=None) -> list:
    """10 (by default) present-day residents, each grounded in a different
    place's history where possible."""
    rng = random.Random(seed)
    used_place_ids = set()
    out = []
    for _ in range(count):
        if not places:
            break
        grounding = _pick_grounding(places, figures, rng, used_place_ids)
        used_place_ids.add(grounding["place"].id)

        char = None
        if config.LLM_FILL_NAMES and llm.available():
            try:
                char = _llm_character(grounding)
            except Exception:
                char = None
        if char is None:
            char = _fallback_character(grounding, rng)
        char["history"] = _generate_life_history(char, grounding, rng)
        out.append(char)
    return out


def generate_one(places: list, figures: list, exclude_place_ids: set = None,
                  force_place_id: str = None, occupation: str = None, sex: str = None,
                  seed=None) -> dict:
    """The single-character equivalent of one generate_characters() loop
    iteration -- for the web app's on-demand "Generate Character" flow
    (history/routes.py's POST /api/history/characters/preview), rather
    than history generation's own fixed batch. `force_place_id`, if given,
    grounds the new character at that exact place instead of the usual
    weighted-random pick; raises ValueError if it doesn't resolve, so the
    route layer can turn that into a clean 400 rather than silently
    falling back to a random place. `occupation`/`sex`, if given, are
    hard constraints handed to the LLM path (and `occupation` alone is
    still honored verbatim by the no-LLM fallback, which has no way to
    act on `sex` -- see _fallback_character's docstring)."""
    if not places:
        raise ValueError("no places to ground a character in")
    rng = random.Random(seed)
    grounding = _pick_grounding(places, figures, rng, exclude_place_ids or set(),
                                 force_place_id=force_place_id)

    char = None
    if config.LLM_FILL_NAMES and llm.available():
        try:
            char = _llm_character(grounding, occupation=occupation, sex=sex)
        except Exception:
            char = None
    if char is None:
        char = _fallback_character(grounding, rng, occupation=occupation, sex=sex)
    char["history"] = _generate_life_history(char, grounding, rng)
    return char
